services:
  llm_searcher:
    build: .
    container_name: llm_searcher.g
    hostname: llm_searcher.g
    restart: no
    networks:
      - internal
    ports:
      - 7860

  llm_searcher_ollama:
    build: ollama
    volumes:
      - ./ollama/data:/root/.ollama
    container_name: llm_searcher_ollama.g
    pull_policy: always
    tty: true
    restart: unless-stopped
    ports:
      - 11434
    environment:
      - OLLAMA_KEEP_ALIVE=5m
    networks:
      - internal
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

networks:
  internal:
    driver: bridge
